CREATE TABLE coleta
(
id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS
IDENTITY,
descricao VARCHAR (100) NOT NULL,
data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE leitura
(
id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS
IDENTITY,
coleta INTEGER NOT NULL,
local VARCHAR (50) NOT NULL,
leitura REAL NOT NULL,
unidade VARCHAR (50) NOT NULL,
atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
constraint fkid foreign key(coleta) references coleta(id)
);